from google import generativeai as genai
from extractor import extract

filename = "ranks.txt"
ranks_text =  open(filename, "r", encoding="utf-8").read()
geo_core_definitions = open("geocore-definitions.txt", "r", encoding="utf-8").read()
bfo_definitions = open("bfo-definitions.txt", "r", encoding="utf-8").read()

resources_folder = "./resources"

API_KEY = "" # insert API key here

genai.configure(api_key=API_KEY)

model_name="gemini-1.5-flash"

system_instruction = """You are an expert in building ontologies for pre-salt petroleum reservoirs.
You will receive five ranked lists of geological term_extraction extracted from research papers and theses. 
Your goal is to consolidate these lists into a single, ranked list of the 200 most relevant and representative term_extraction for ontology development. 
Prioritize broader concepts, ensure relevance to pre-salt petroleum reservoirs, and aim for term_extraction that are clear, unambiguous, and suitable for a formal ontology.  
Note that the lists may contain variations of term_extraction (e.g., singular/plural, abbreviations).  
You may transform term_extraction to improve consistency and clarity, but must document any transformations.  
You will also categorize each term using the provided GeoCore or BFO definitions. If none of the GeoCore definitions are suitable for a term, then you should use BFO definitions.
"""

prompt = f"""You are provided with five ranked lists of term_extraction related to pre-salt geology and petroleum systems. 
These lists were generated by analyzing a substantial collection of text from research papers and master theses. 
Your task is to consolidate these lists into a single ranked list of the 200 most relevant and representative term_extraction for building an ontology of pre-salt petroleum reservoirs, 
considering that this ontology will be evaluated by geologists.  
You will also categorize each term using the provided GeoCore and BFO definitions.

Instructions:

1. List Consolidation and Transformation:
- Combine the five lists into a single list.
- Identify and group variations of the same term (e.g., "carbonate platform," "carbonate platforms").
- Choose the most appropriate form of each term for the ontology (usually the singular, most complete form).
- Remove any duplicate term_extraction after transformation.

2. Ranking Criteria:
- Prioritize term_extraction that appear higher in the original rankings within each list.
- Consider the frequency of a term's appearance (or its variations) across the five lists as an indicator of importance.
- Favor term_extraction that are broader, more general concepts, avoiding overly specific examples or data points.

3. Term Optimization for Geologist Evaluation:
- Ensure that the chosen term_extraction are relevant to pre-salt petroleum reservoirs.
- Consider the level of granularity – term_extraction should be general enough for broad applicability but specific enough to be meaningful.
- **Relevance to Pre-salt:**  Prioritize term_extraction directly related to the unique geological characteristics of pre-salt reservoirs.
- **Representativeness:** Favor term_extraction that represent broader concepts and are likely to have multiple instances or subclasses within the ontology. 
Avoid overly specific term_extraction that are essentially instances (e.g., specific formation names, well names).
- **Ontological Suitability:**  Prefer term_extraction that can be easily defined and related to other term_extraction in a formal ontology. 
Avoid term_extraction that are ambiguous, context-dependent, or represent complex processes that might be better represented as relations rather than classes.

4. Categorization (Crucial):
- For each selected term, assign it to the *most appropriate* category from the following *subset* of GeoCore and BFO definitions (provided below). 
If a term doesn't fit cleanly into one of GeoCore definitions, then use BFO definitions.  Be consistent in your categorization.  
- Provide a justification for each term's categorization, explaining why the chosen GeoCore or BFO definition is the most appropriate.

**GeoCore definitions:**
{geo_core_definitions}

**BFO definitions:**
{bfo_definitions}

5. Output Format:
- Provide the output in a tabular format with the following columns:  Term, Transformed Term (if applicable), Rationale for Transformation, GeoCore/BFO Category.

Lists to be ranked: {ranks_text}
"""
generation_config = genai.GenerationConfig(
    temperature=0.1,
)

model = genai.GenerativeModel(model_name=model_name,
                              system_instruction=system_instruction,
                              generation_config=generation_config)

response = model.generate_content(prompt)
print(response.text)

print("total tokens: ", model.count_tokens(prompt + ranks_text))